FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN python -m pip install --no-cache-dir --upgrade pip
RUN python -m pip install --no-cache-dir "setuptools<81" wheel
RUN pip install --no-cache-dir -r requirements.txt

COPY . .